
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AsideMenu': typeof import("../components/AsideMenu.vue")['default']
    'AsideMenuItem': typeof import("../components/AsideMenuItem.vue")['default']
    'AsideMenuLayer': typeof import("../components/AsideMenuLayer.vue")['default']
    'AsideMenuList': typeof import("../components/AsideMenuList.vue")['default']
    'BaseButton': typeof import("../components/BaseButton.vue")['default']
    'BaseButtons': typeof import("../components/BaseButtons.vue")['default']
    'BaseDivider': typeof import("../components/BaseDivider.vue")['default']
    'BaseIcon': typeof import("../components/BaseIcon.vue")['default']
    'BaseLevel': typeof import("../components/BaseLevel.vue")['default']
    'BaseMessage': typeof import("../components/BaseMessage.vue")['default']
    'BaseMessageList': typeof import("../components/BaseMessageList.vue")['default']
    'CardBox': typeof import("../components/CardBox.vue")['default']
    'CardBoxClient': typeof import("../components/CardBoxClient.vue")['default']
    'CardBoxModal': typeof import("../components/CardBoxModal.vue")['default']
    'CardBoxScrollable': typeof import("../components/CardBoxScrollable.vue")['default']
    'CardBoxTransaction': typeof import("../components/CardBoxTransaction.vue")['default']
    'CardBoxWidget': typeof import("../components/CardBoxWidget.vue")['default']
    'CardComponent': typeof import("../components/CardComponent.vue")['default']
    'ChartsLineChart': typeof import("../components/Charts/LineChart.vue")['default']
    'ChartsChartConfig': typeof import("../components/Charts/chart.config")['default']
    'FooterBar': typeof import("../components/FooterBar.vue")['default']
    'FormCheckRadio': typeof import("../components/FormCheckRadio.vue")['default']
    'FormCheckRadioGroup': typeof import("../components/FormCheckRadioGroup.vue")['default']
    'FormControl': typeof import("../components/FormControl.vue")['default']
    'FormControlIcon': typeof import("../components/FormControlIcon.vue")['default']
    'FormField': typeof import("../components/FormField.vue")['default']
    'FormFilePicker': typeof import("../components/FormFilePicker.vue")['default']
    'GroupsIdSelector': typeof import("../components/GroupsIdSelector.vue")['default']
    'IconRounded': typeof import("../components/IconRounded.vue")['default']
    'JbButton': typeof import("../components/JbButton.vue")['default']
    'JustboilLogo': typeof import("../components/JustboilLogo.vue")['default']
    'NavBar': typeof import("../components/NavBar.vue")['default']
    'NavBarItem': typeof import("../components/NavBarItem.vue")['default']
    'NavBarItemPlain': typeof import("../components/NavBarItemPlain.vue")['default']
    'NavBarMenuList': typeof import("../components/NavBarMenuList.vue")['default']
    'NotificationBar': typeof import("../components/NotificationBar.vue")['default']
    'NotificationBarInCard': typeof import("../components/NotificationBarInCard.vue")['default']
    'NumberDynamic': typeof import("../components/NumberDynamic.vue")['default']
    'OverlayLayer': typeof import("../components/OverlayLayer.vue")['default']
    'PillTag': typeof import("../components/PillTag.vue")['default']
    'PillTagTrend': typeof import("../components/PillTagTrend.vue")['default']
    'ScheduleFormCard': typeof import("../components/ScheduleFormCard.vue")['default']
    'SectionBanner': typeof import("../components/SectionBanner.vue")['default']
    'SectionBannerStarOnGitHub': typeof import("../components/SectionBannerStarOnGitHub.vue")['default']
    'SectionFullScreen': typeof import("../components/SectionFullScreen.vue")['default']
    'SectionMain': typeof import("../components/SectionMain.vue")['default']
    'SectionTitle': typeof import("../components/SectionTitle.vue")['default']
    'SectionTitleLine': typeof import("../components/SectionTitleLine.vue")['default']
    'SectionTitleLineWithButton': typeof import("../components/SectionTitleLineWithButton.vue")['default']
    'TableChatsClients': typeof import("../components/TableChatsClients.vue")['default']
    'TableCheckboxCell': typeof import("../components/TableCheckboxCell.vue")['default']
    'TableGroupsClients': typeof import("../components/TableGroupsClients.vue")['default']
    'TableMessages': typeof import("../components/TableMessages.vue")['default']
    'TableSampleAdmins': typeof import("../components/TableSampleAdmins.vue")['default']
    'TableSampleClients': typeof import("../components/TableSampleClients.vue")['default']
    'TableSampleGroups': typeof import("../components/TableSampleGroups.vue")['default']
    'UserAvatar': typeof import("../components/UserAvatar.vue")['default']
    'UserAvatarCurrentUser': typeof import("../components/UserAvatarCurrentUser.vue")['default']
    'UserCard': typeof import("../components/UserCard.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAsideMenu': typeof import("../components/AsideMenu.vue")['default']
    'LazyAsideMenuItem': typeof import("../components/AsideMenuItem.vue")['default']
    'LazyAsideMenuLayer': typeof import("../components/AsideMenuLayer.vue")['default']
    'LazyAsideMenuList': typeof import("../components/AsideMenuList.vue")['default']
    'LazyBaseButton': typeof import("../components/BaseButton.vue")['default']
    'LazyBaseButtons': typeof import("../components/BaseButtons.vue")['default']
    'LazyBaseDivider': typeof import("../components/BaseDivider.vue")['default']
    'LazyBaseIcon': typeof import("../components/BaseIcon.vue")['default']
    'LazyBaseLevel': typeof import("../components/BaseLevel.vue")['default']
    'LazyBaseMessage': typeof import("../components/BaseMessage.vue")['default']
    'LazyBaseMessageList': typeof import("../components/BaseMessageList.vue")['default']
    'LazyCardBox': typeof import("../components/CardBox.vue")['default']
    'LazyCardBoxClient': typeof import("../components/CardBoxClient.vue")['default']
    'LazyCardBoxModal': typeof import("../components/CardBoxModal.vue")['default']
    'LazyCardBoxScrollable': typeof import("../components/CardBoxScrollable.vue")['default']
    'LazyCardBoxTransaction': typeof import("../components/CardBoxTransaction.vue")['default']
    'LazyCardBoxWidget': typeof import("../components/CardBoxWidget.vue")['default']
    'LazyCardComponent': typeof import("../components/CardComponent.vue")['default']
    'LazyChartsLineChart': typeof import("../components/Charts/LineChart.vue")['default']
    'LazyChartsChartConfig': typeof import("../components/Charts/chart.config")['default']
    'LazyFooterBar': typeof import("../components/FooterBar.vue")['default']
    'LazyFormCheckRadio': typeof import("../components/FormCheckRadio.vue")['default']
    'LazyFormCheckRadioGroup': typeof import("../components/FormCheckRadioGroup.vue")['default']
    'LazyFormControl': typeof import("../components/FormControl.vue")['default']
    'LazyFormControlIcon': typeof import("../components/FormControlIcon.vue")['default']
    'LazyFormField': typeof import("../components/FormField.vue")['default']
    'LazyFormFilePicker': typeof import("../components/FormFilePicker.vue")['default']
    'LazyGroupsIdSelector': typeof import("../components/GroupsIdSelector.vue")['default']
    'LazyIconRounded': typeof import("../components/IconRounded.vue")['default']
    'LazyJbButton': typeof import("../components/JbButton.vue")['default']
    'LazyJustboilLogo': typeof import("../components/JustboilLogo.vue")['default']
    'LazyNavBar': typeof import("../components/NavBar.vue")['default']
    'LazyNavBarItem': typeof import("../components/NavBarItem.vue")['default']
    'LazyNavBarItemPlain': typeof import("../components/NavBarItemPlain.vue")['default']
    'LazyNavBarMenuList': typeof import("../components/NavBarMenuList.vue")['default']
    'LazyNotificationBar': typeof import("../components/NotificationBar.vue")['default']
    'LazyNotificationBarInCard': typeof import("../components/NotificationBarInCard.vue")['default']
    'LazyNumberDynamic': typeof import("../components/NumberDynamic.vue")['default']
    'LazyOverlayLayer': typeof import("../components/OverlayLayer.vue")['default']
    'LazyPillTag': typeof import("../components/PillTag.vue")['default']
    'LazyPillTagTrend': typeof import("../components/PillTagTrend.vue")['default']
    'LazyScheduleFormCard': typeof import("../components/ScheduleFormCard.vue")['default']
    'LazySectionBanner': typeof import("../components/SectionBanner.vue")['default']
    'LazySectionBannerStarOnGitHub': typeof import("../components/SectionBannerStarOnGitHub.vue")['default']
    'LazySectionFullScreen': typeof import("../components/SectionFullScreen.vue")['default']
    'LazySectionMain': typeof import("../components/SectionMain.vue")['default']
    'LazySectionTitle': typeof import("../components/SectionTitle.vue")['default']
    'LazySectionTitleLine': typeof import("../components/SectionTitleLine.vue")['default']
    'LazySectionTitleLineWithButton': typeof import("../components/SectionTitleLineWithButton.vue")['default']
    'LazyTableChatsClients': typeof import("../components/TableChatsClients.vue")['default']
    'LazyTableCheckboxCell': typeof import("../components/TableCheckboxCell.vue")['default']
    'LazyTableGroupsClients': typeof import("../components/TableGroupsClients.vue")['default']
    'LazyTableMessages': typeof import("../components/TableMessages.vue")['default']
    'LazyTableSampleAdmins': typeof import("../components/TableSampleAdmins.vue")['default']
    'LazyTableSampleClients': typeof import("../components/TableSampleClients.vue")['default']
    'LazyTableSampleGroups': typeof import("../components/TableSampleGroups.vue")['default']
    'LazyUserAvatar': typeof import("../components/UserAvatar.vue")['default']
    'LazyUserAvatarCurrentUser': typeof import("../components/UserAvatarCurrentUser.vue")['default']
    'LazyUserCard': typeof import("../components/UserCard.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AsideMenu: typeof import("../components/AsideMenu.vue")['default']
export const AsideMenuItem: typeof import("../components/AsideMenuItem.vue")['default']
export const AsideMenuLayer: typeof import("../components/AsideMenuLayer.vue")['default']
export const AsideMenuList: typeof import("../components/AsideMenuList.vue")['default']
export const BaseButton: typeof import("../components/BaseButton.vue")['default']
export const BaseButtons: typeof import("../components/BaseButtons.vue")['default']
export const BaseDivider: typeof import("../components/BaseDivider.vue")['default']
export const BaseIcon: typeof import("../components/BaseIcon.vue")['default']
export const BaseLevel: typeof import("../components/BaseLevel.vue")['default']
export const BaseMessage: typeof import("../components/BaseMessage.vue")['default']
export const BaseMessageList: typeof import("../components/BaseMessageList.vue")['default']
export const CardBox: typeof import("../components/CardBox.vue")['default']
export const CardBoxClient: typeof import("../components/CardBoxClient.vue")['default']
export const CardBoxModal: typeof import("../components/CardBoxModal.vue")['default']
export const CardBoxScrollable: typeof import("../components/CardBoxScrollable.vue")['default']
export const CardBoxTransaction: typeof import("../components/CardBoxTransaction.vue")['default']
export const CardBoxWidget: typeof import("../components/CardBoxWidget.vue")['default']
export const CardComponent: typeof import("../components/CardComponent.vue")['default']
export const ChartsLineChart: typeof import("../components/Charts/LineChart.vue")['default']
export const ChartsChartConfig: typeof import("../components/Charts/chart.config")['default']
export const FooterBar: typeof import("../components/FooterBar.vue")['default']
export const FormCheckRadio: typeof import("../components/FormCheckRadio.vue")['default']
export const FormCheckRadioGroup: typeof import("../components/FormCheckRadioGroup.vue")['default']
export const FormControl: typeof import("../components/FormControl.vue")['default']
export const FormControlIcon: typeof import("../components/FormControlIcon.vue")['default']
export const FormField: typeof import("../components/FormField.vue")['default']
export const FormFilePicker: typeof import("../components/FormFilePicker.vue")['default']
export const GroupsIdSelector: typeof import("../components/GroupsIdSelector.vue")['default']
export const IconRounded: typeof import("../components/IconRounded.vue")['default']
export const JbButton: typeof import("../components/JbButton.vue")['default']
export const JustboilLogo: typeof import("../components/JustboilLogo.vue")['default']
export const NavBar: typeof import("../components/NavBar.vue")['default']
export const NavBarItem: typeof import("../components/NavBarItem.vue")['default']
export const NavBarItemPlain: typeof import("../components/NavBarItemPlain.vue")['default']
export const NavBarMenuList: typeof import("../components/NavBarMenuList.vue")['default']
export const NotificationBar: typeof import("../components/NotificationBar.vue")['default']
export const NotificationBarInCard: typeof import("../components/NotificationBarInCard.vue")['default']
export const NumberDynamic: typeof import("../components/NumberDynamic.vue")['default']
export const OverlayLayer: typeof import("../components/OverlayLayer.vue")['default']
export const PillTag: typeof import("../components/PillTag.vue")['default']
export const PillTagTrend: typeof import("../components/PillTagTrend.vue")['default']
export const ScheduleFormCard: typeof import("../components/ScheduleFormCard.vue")['default']
export const SectionBanner: typeof import("../components/SectionBanner.vue")['default']
export const SectionBannerStarOnGitHub: typeof import("../components/SectionBannerStarOnGitHub.vue")['default']
export const SectionFullScreen: typeof import("../components/SectionFullScreen.vue")['default']
export const SectionMain: typeof import("../components/SectionMain.vue")['default']
export const SectionTitle: typeof import("../components/SectionTitle.vue")['default']
export const SectionTitleLine: typeof import("../components/SectionTitleLine.vue")['default']
export const SectionTitleLineWithButton: typeof import("../components/SectionTitleLineWithButton.vue")['default']
export const TableChatsClients: typeof import("../components/TableChatsClients.vue")['default']
export const TableCheckboxCell: typeof import("../components/TableCheckboxCell.vue")['default']
export const TableGroupsClients: typeof import("../components/TableGroupsClients.vue")['default']
export const TableMessages: typeof import("../components/TableMessages.vue")['default']
export const TableSampleAdmins: typeof import("../components/TableSampleAdmins.vue")['default']
export const TableSampleClients: typeof import("../components/TableSampleClients.vue")['default']
export const TableSampleGroups: typeof import("../components/TableSampleGroups.vue")['default']
export const UserAvatar: typeof import("../components/UserAvatar.vue")['default']
export const UserAvatarCurrentUser: typeof import("../components/UserAvatarCurrentUser.vue")['default']
export const UserCard: typeof import("../components/UserCard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAsideMenu: typeof import("../components/AsideMenu.vue")['default']
export const LazyAsideMenuItem: typeof import("../components/AsideMenuItem.vue")['default']
export const LazyAsideMenuLayer: typeof import("../components/AsideMenuLayer.vue")['default']
export const LazyAsideMenuList: typeof import("../components/AsideMenuList.vue")['default']
export const LazyBaseButton: typeof import("../components/BaseButton.vue")['default']
export const LazyBaseButtons: typeof import("../components/BaseButtons.vue")['default']
export const LazyBaseDivider: typeof import("../components/BaseDivider.vue")['default']
export const LazyBaseIcon: typeof import("../components/BaseIcon.vue")['default']
export const LazyBaseLevel: typeof import("../components/BaseLevel.vue")['default']
export const LazyBaseMessage: typeof import("../components/BaseMessage.vue")['default']
export const LazyBaseMessageList: typeof import("../components/BaseMessageList.vue")['default']
export const LazyCardBox: typeof import("../components/CardBox.vue")['default']
export const LazyCardBoxClient: typeof import("../components/CardBoxClient.vue")['default']
export const LazyCardBoxModal: typeof import("../components/CardBoxModal.vue")['default']
export const LazyCardBoxScrollable: typeof import("../components/CardBoxScrollable.vue")['default']
export const LazyCardBoxTransaction: typeof import("../components/CardBoxTransaction.vue")['default']
export const LazyCardBoxWidget: typeof import("../components/CardBoxWidget.vue")['default']
export const LazyCardComponent: typeof import("../components/CardComponent.vue")['default']
export const LazyChartsLineChart: typeof import("../components/Charts/LineChart.vue")['default']
export const LazyChartsChartConfig: typeof import("../components/Charts/chart.config")['default']
export const LazyFooterBar: typeof import("../components/FooterBar.vue")['default']
export const LazyFormCheckRadio: typeof import("../components/FormCheckRadio.vue")['default']
export const LazyFormCheckRadioGroup: typeof import("../components/FormCheckRadioGroup.vue")['default']
export const LazyFormControl: typeof import("../components/FormControl.vue")['default']
export const LazyFormControlIcon: typeof import("../components/FormControlIcon.vue")['default']
export const LazyFormField: typeof import("../components/FormField.vue")['default']
export const LazyFormFilePicker: typeof import("../components/FormFilePicker.vue")['default']
export const LazyGroupsIdSelector: typeof import("../components/GroupsIdSelector.vue")['default']
export const LazyIconRounded: typeof import("../components/IconRounded.vue")['default']
export const LazyJbButton: typeof import("../components/JbButton.vue")['default']
export const LazyJustboilLogo: typeof import("../components/JustboilLogo.vue")['default']
export const LazyNavBar: typeof import("../components/NavBar.vue")['default']
export const LazyNavBarItem: typeof import("../components/NavBarItem.vue")['default']
export const LazyNavBarItemPlain: typeof import("../components/NavBarItemPlain.vue")['default']
export const LazyNavBarMenuList: typeof import("../components/NavBarMenuList.vue")['default']
export const LazyNotificationBar: typeof import("../components/NotificationBar.vue")['default']
export const LazyNotificationBarInCard: typeof import("../components/NotificationBarInCard.vue")['default']
export const LazyNumberDynamic: typeof import("../components/NumberDynamic.vue")['default']
export const LazyOverlayLayer: typeof import("../components/OverlayLayer.vue")['default']
export const LazyPillTag: typeof import("../components/PillTag.vue")['default']
export const LazyPillTagTrend: typeof import("../components/PillTagTrend.vue")['default']
export const LazyScheduleFormCard: typeof import("../components/ScheduleFormCard.vue")['default']
export const LazySectionBanner: typeof import("../components/SectionBanner.vue")['default']
export const LazySectionBannerStarOnGitHub: typeof import("../components/SectionBannerStarOnGitHub.vue")['default']
export const LazySectionFullScreen: typeof import("../components/SectionFullScreen.vue")['default']
export const LazySectionMain: typeof import("../components/SectionMain.vue")['default']
export const LazySectionTitle: typeof import("../components/SectionTitle.vue")['default']
export const LazySectionTitleLine: typeof import("../components/SectionTitleLine.vue")['default']
export const LazySectionTitleLineWithButton: typeof import("../components/SectionTitleLineWithButton.vue")['default']
export const LazyTableChatsClients: typeof import("../components/TableChatsClients.vue")['default']
export const LazyTableCheckboxCell: typeof import("../components/TableCheckboxCell.vue")['default']
export const LazyTableGroupsClients: typeof import("../components/TableGroupsClients.vue")['default']
export const LazyTableMessages: typeof import("../components/TableMessages.vue")['default']
export const LazyTableSampleAdmins: typeof import("../components/TableSampleAdmins.vue")['default']
export const LazyTableSampleClients: typeof import("../components/TableSampleClients.vue")['default']
export const LazyTableSampleGroups: typeof import("../components/TableSampleGroups.vue")['default']
export const LazyUserAvatar: typeof import("../components/UserAvatar.vue")['default']
export const LazyUserAvatarCurrentUser: typeof import("../components/UserAvatarCurrentUser.vue")['default']
export const LazyUserCard: typeof import("../components/UserCard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
