// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.07.2024, 17:54:38
const configMerger = require("/Users/admin/work/teleos-admin/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/admin/work/teleos-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/plugins/**/*.{js,ts,mjs}","/Users/admin/work/teleos-admin/composables/**/*.{js,ts,mjs}","/Users/admin/work/teleos-admin/utils/**/*.{js,ts,mjs}","/Users/admin/work/teleos-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/admin/work/teleos-admin/app.config.{js,ts,mjs}"] }));

module.exports = config
