// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.01.2025, 14:31:18
const configMerger = require("F:/work/xram-admin/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["F:/work/xram-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/plugins/**/*.{js,ts,mjs}","F:/work/xram-admin/composables/**/*.{js,ts,mjs}","F:/work/xram-admin/utils/**/*.{js,ts,mjs}","F:/work/xram-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/work/xram-admin/app.config.{js,ts,mjs}"] } }));

module.exports = config
